# Generated by Django 4.2 on 2023-05-05 21:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0002_book_cover"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="book",
            constraint=models.CheckConstraint(
                check=models.Q(("inventory__gte", 0)), name="inventory_non_negative"
            ),
        ),
    ]
