# Generated by Django 4.2 on 2023-04-20 10:28

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowing',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='borrowing',
            name='actual_return_date',
            field=models.DateField(blank=True, help_text='The date when the book was actually returned.', null=True),
        ),
        migrations.AlterField(
            model_name='borrowing',
            name='borrow_date',
            field=models.DateField(help_text='The date when the book was borrowed.', validators=[django.core.validators.MinValueValidator(limit_value=datetime.date.today)]),
        ),
        migrations.AlterField(
            model_name='borrowing',
            name='expected_return_date',
            field=models.DateField(help_text='The date when the book is expected to be returned.', validators=[django.core.validators.MinValueValidator(limit_value=datetime.date.today)]),
        ),
    ]
