# Generated by Django 4.2 on 2023-05-02 17:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("borrowings", "0005_alter_borrowing_borrow_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="borrowing",
            name="borrow_date",
            field=models.DateField(
                auto_now_add=True, help_text="The date when the book was borrowed."
            ),
        ),
        migrations.AlterField(
            model_name="borrowing",
            name="expected_return_date",
            field=models.DateField(
                help_text="The date when the book is expected to be returned."
            ),
        ),
    ]
